### ISSUE TITLE
Unexpected failure converting in Python 3 when using dry run

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/zodbupdate#22]
The README states that it is possible to do a one-step conversion of a ZODB created under Python 2 to a Python 3 compatible format. One important caveat is missing here, though. This does not apply to "older" ZODB files coming from, say, Zope 2.13.

The issue is the Data.fs magic number. Older Data.fs files will be `FS21`, which the ZODB code under Python 3 completely refuses to open. They open fine with the same ZODB code under Python 2.

I do not know if this is intended behavior in zodbupdate and just needs documentation, or if it is a bug where e.g. zodbupdate could rewrite the magic number before the ZODB code attempts to open the file.

This is already causing confusion, see zopefoundation/Zope#661.

**Comment by mgedmin** [comment]
Uh, here's the code that rewrites the magic number *before* opening the file if you run zodbupdate --convert-py3 on Python 3:
https://github.com/zopefoundation/zodbupdate/blob/9e47c6097c774f33699e2b6d729af62928e72ddc/src/zodbupdate/main.py#L190-L194

**Comment by dataflake** [comment]
I see where the issue is. I tested with `dry_run`. In that case you get the exception I show at zopefoundation/Zope#661. So there's still a bug in that behavior.

**Comment by dataflake** [comment]
OK, so the real issue is this: The rewriting of the ZODB magic number before the ZODB code opens the database only happens when run without dry_run. When dry_run is used, you get the (unhelpful) traceback.

Possible solutions would be to either present some message that tells the user dry_run won't work for the database, or two magic number rewrite steps, where one happens after the zodbupdate run to restore the old magic number.

**Comment by mgedmin** [comment]
I do not like the idea of `--dry-run` making changes then (hopefully) undoing them later.

Maybe FileStorage could be subclassed/monkey-patched to accept the Python 2 magic string under these very special circumstances?

**Comment by dataflake** [comment]
Yeah, that's a suitable solution, too.

**Comment by dataflake** [comment]
I have looked at this again and it seems no matter what I do to try and change the value of `packed_version` (or `FILESTORAGE_MAGIC`) inside that `FileStorage` module, during the instantiation of the `FileStorage` instance the value is always back at `FS30` and it fails.

So the upshot is, you can run the conversion on Python 3, but dry-run or running `zodbverify` before the conversion will always fail. I don't know how to proceed on this without changing code in the ZODB package itself, which I do not want to do.

**Comment by icemac** [comment]
So let's document that `--dry-run` does not work under these circumstances. As conversion should be done on a copy, I see no need for such a switch.

**Comment by mgedmin** [comment]
`--dry-run` may be pointless for a conversion (if you run on Python 3), but it is useful for regular zodbupdate jobs (or conversion if you run on Python 2).

E.g. I'm currently using zodbupdate --dry-run (on Python 3) after doing the conversion (on Python 2) to verify that all the object pickles can be unpickled.

+1 for documenting that --dry-run + --convert-py3 + sys.version_info[0] >= 3 is not going to work, preferably by having the code itself sys.exit() with a clear message rather than a traceback.

(Although I still would prefer to make some changes to ZODB to make it possible to accept different magic values via a custom subclass or hook of some kind.  Well, when I say "prefer" I mean "if somebody else wants to do that because I already have too much things on my plates".)

**Comment by icemac** [comment]
@mgedmin To check whether all pickles in a ZODB can be unpickled I am using [zodbverify](https://pypi.org/project/zodbverify/) which does a great job.
